### ISSUE TITLE
Static Analysis as a Ground Truth

### ISSUE THREAD

**Issue by bengsparks** [pvs-hd-tea/PyTypes#14]
How can we leverage types generated by mypy's stubgen for our type inference?
Is it even feasible to do this, or is it a waste of time?

**Comment by RecurvedBow** [comment]
mypy can infer the type of a variable if a value of an obvious type (f. ex. int, str) is assigned to it or the assigned function return value has a type hint. If it is not provided, mypy will infer any.

Source: https://mypy.readthedocs.io/en/stable/type_inference_and_annotations.html

Will conduct some further analysis whether mypy can infer function arguments and whether type inference of one variable can lead to inference of another.

**Comment by RecurvedBow** [comment]
To get the inferred types of variables using mypy, the functions reveal_type(any_variable) and reveal_locals are used (Gets the types of local variables). However, they are mypy-only and can not be executed using any python interpreter. This means that the command mypy python_files.py has to be executed and the functions reveal_type & reveal_locals have to be added in the file. Designing a script which appends these functions in the file is possible, but will require a lot of effort. This might be a waste of time as we also would have to develop a script to get the types of the variables.

Will now check the capabilities of mypy inference on sample files.

**Comment by RecurvedBow** [comment]
Check 1:
reveal_locals(), despite not being recognized by the python interpreter works by adding it within a function. To get the results, has to be before a return or a raise Error. Additionally, the indent level still has to be correct.
reveal_locals() will reveal the infered type of local variables and function arguments. It does not reveal types of self members nor function return values. It will also not reveal types of local variables defined after the reveal_locals statement.
According to the mypy documentation, the inference is never wrong as there is no randomness nor statistical machine learning involved (But the infered type might be set too broad (Any)). The reason that reveal_locals returns types is because the sample file contains type hints, which mypy uses to infer the type.
 
Note: The lines where the type is inferred is at the line where reveal_locals is called and not where the variables are defined (compared to the tracer).
Note 2: A script which parses the revealed type name to the actual type (in Python) might be necessary.
![grafik](https://user-images.githubusercontent.com/101172476/175827147-60a28d1b-c811-413d-8f0f-0ece2c061fd8.png)

**Comment by RecurvedBow** [comment]
What can be noted is that mypy has the type narrowing feature: If an function argument is checked with isinstance for example, then mypy will infer that that argument is of that checked type. This additional data would be useful.

**Comment by RecurvedBow** [comment]
Issues which would be needed to integrate mypy inference assist with current tracer:

- Append reveal_type & reveal_locals in any python file
- Execution and collection of infered type
- Collection converted into (trace-data similar) data (& Dropping of any)
- Handling of special cases such as Union
- Detection which data belongs to the corresponding trace data subset
- Unification with trace data
(- Differences in %)

Estimated effort (2 - 3 Sprints/ 4 - 6 weeks)

**Comment by RecurvedBow** [comment]
Summary: The infered types are of the category Function Argument & Local Variable (No Class Members nor Function Return Value). The types are infered logically using existing type hints, type narrowing or just checking the directly assigned value if it is clear (a = 1 -> int). There is no statistics involved, so the infered types (except for inferred any) should be technically 100% correct. However, without any type hints, no useful inference data is generated.

Perhaps further research might change the current insights, but this is the following conclusion:
- Yes, the mypy type inference is useful and help in discovering new possible types to infer.
- However, the effort required to use the mypy inference as ground truth is too high (and the discovered insights might be rather few if the tests cover many cases).

-> Using mypy static type inference as ground truth is NOT recommended; gain is not worth it.
